layout_spectrum: 1
typography_spectrum: 0.5269815
color:
  lightness: 0.3279932
  brandStrength: 1
  saturation: 0.6770658
  rhythmicContrast: 0.9738617
  brandColors:
    - '#0C0A0B'
    - '#41271A'
    - '#785738'
    - '#4D3E2D'
    - '#5F4832'
name: Lentil soup
